### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by sthaiya** [heroiclabs/nakama-java#32] opened 2020-06-03 11:28 UTC
Trying to compile nakama-java fails with these errors

warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/sam/nakama-java/src/main/java/com/heroiclabs/nakama/Client.java:884: error: cannot find symbol
    ListenableFuture<FriendList> listFriends(@NonNull final Session session);
                     ^
  symbol:   class FriendList
  location: interface Client
/home/sam/nakama-java/src/main/java/com/heroiclabs/nakama/Client.java:895: error: cannot find symbol
    ListenableFuture<FriendList> listFriends(@NonNull final Session session, final int state, final int limit, final String cursor);
                     ^
  symbol:   class FriendList
  location: interface Client
/home/sam/nakama-java/src/main/java/com/heroiclabs/nakama/DefaultClient.java:1027: error: cannot find symbol
    public ListenableFuture<FriendList> listFriends(@NonNull final Session session) {
                            ^
  symbol:   class FriendList
  location: class DefaultClient
/home/sam/nakama-java/src/main/java/com/heroiclabs/nakama/DefaultClient.java:1032: error: cannot find symbol
    public ListenableFuture<FriendList> listFriends(@NonNull final Session session, final int state, final int limit, final String cursor) {
                            ^
  symbol:   class FriendList
  location: class DefaultClient
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:530: error: cannot find symbol
  private static volatile io.grpc.MethodDescriptor<com.heroiclabs.nakama.api.Event,
                                                                            ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:538: error: cannot find symbol
  public static io.grpc.MethodDescriptor<com.heroiclabs.nakama.api.Event,
                                                                  ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1057: error: cannot find symbol
  private static volatile io.grpc.MethodDescriptor<com.heroiclabs.nakama.api.ListFriendsRequest,
                                                                            ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1058: error: cannot find symbol
      com.heroiclabs.nakama.api.FriendList> getListFriendsMethod;
                               ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1065: error: cannot find symbol
  public static io.grpc.MethodDescriptor<com.heroiclabs.nakama.api.ListFriendsRequest,
                                                                  ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1066: error: cannot find symbol
      com.heroiclabs.nakama.api.FriendList> getListFriendsMethod() {
                               ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:4461: error: cannot find symbol
        com.heroiclabs.nakama.api.Event request) {
                                 ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:4648: error: cannot find symbol
        com.heroiclabs.nakama.api.ListFriendsRequest request) {
                                 ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:4647: error: cannot find symbol
    public com.google.common.util.concurrent.ListenableFuture<com.heroiclabs.nakama.api.FriendList> listFriends(
                                                                                       ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3154: error: cannot find symbol
    public void event(com.heroiclabs.nakama.api.Event request,
                                               ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3341: error: cannot find symbol
    public void listFriends(com.heroiclabs.nakama.api.ListFriendsRequest request,
                                                     ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3342: error: cannot find symbol
        io.grpc.stub.StreamObserver<com.heroiclabs.nakama.api.FriendList> responseObserver) {
                                                             ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3821: error: cannot find symbol
    public com.google.protobuf.Empty event(com.heroiclabs.nakama.api.Event request) {
                                                                    ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3991: error: cannot find symbol
    public com.heroiclabs.nakama.api.FriendList listFriends(com.heroiclabs.nakama.api.ListFriendsRequest request) {
                                                                                     ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:3991: error: cannot find symbol
    public com.heroiclabs.nakama.api.FriendList listFriends(com.heroiclabs.nakama.api.ListFriendsRequest request) {
                                    ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:2090: error: cannot find symbol
    public void event(com.heroiclabs.nakama.api.Event request,
                                               ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:2260: error: cannot find symbol
    public void listFriends(com.heroiclabs.nakama.api.ListFriendsRequest request,
                                                     ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:2261: error: cannot find symbol
        io.grpc.stub.StreamObserver<com.heroiclabs.nakama.api.FriendList> responseObserver) {
                                                             ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:535: error: cannot find symbol
      requestType = com.heroiclabs.nakama.api.Event.class,
                                             ^
  symbol:   class Event
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1062: error: cannot find symbol
      requestType = com.heroiclabs.nakama.api.ListFriendsRequest.class,
                                             ^
  symbol:   class ListFriendsRequest
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api/NakamaGrpc.java:1063: error: cannot find symbol
      responseType = com.heroiclabs.nakama.api.FriendList.class,
                                              ^
  symbol:   class FriendList
  location: package com.heroiclabs.nakama.api
/home/sam/nakama-java/src/main/java/com/heroiclabs/nakama/DefaultClient.java:1033: error: Cannot use 'var' here because initializer expression does not have a representable type: Type cannot be resolved
        final var builder = ListFriendsRequest.newBuilder();

**Comment by mofirouz** [comment] 2020-06-03 11:29
Please make sure you use Gradle 4.10 (and not Gradle 5 or later) - this is a known issue.

**Comment by sthaiya** [comment] 2020-06-03 11:46
I am using gradle 4.10

------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Linux 4.15.0-101-generic amd64

**Comment by sthaiya** [comment] 2020-06-03 12:54
Looking here 

https://github.com/heroiclabs/nakama-java/tree/master/build/generated/source/proto/main/javalite/com/heroiclabs/nakama/api

there is no Event class. Could this be the cause?

**Comment by novabyte** [comment] 2020-06-03 14:15
@sthaiya The events API was added to the server in a later release. I can't quite tell from the errors though whether that's the root causes of the unresolved types. IIRC the codebase uses Lombok for some code generation; do you have that configured and working correctly?

**Comment by sthaiya** [comment] 2020-06-03 15:02
I think may have missed something there, let me have a relook at Lombok again. Will update

**Comment by sthaiya** [comment] 2020-06-03 15:41
I see lombok is a dependency and I have liblombok-java v1.16 installed. So i guess it is well set but I may be missing anything. Is there any setting needed for lombok

**Comment by sthaiya** [comment] 2020-06-04 19:44
Any pointer on how to fix this?

**Comment by hamentgm** [comment] 2020-07-13 02:53
@sthaiya you can generate missing classes from below Proto.
https://github.com/heroiclabs/nakama-common/blob/master/api/api.proto

**Comment by mthakuri** [comment] 2020-07-18 15:23
@hamentgm You comment helped me with the direction to go. Now I'm able to compile the code although test cases are failing. Will look into it next. Anyone know which server version this client v2.0.4 made for? 2.7.0?

**Comment by mofirouz** [comment] 2020-07-20 14:21
@mthakuri At least 2.7.0 - if the tests are failing, make sure your local Nakama server loads [these modules](https://github.com/heroiclabs/nakama/tree/master/data/modules).

**Comment by sthaiya** [comment] 2020-07-21 06:39
Thanks @hamentgm. however I am still missing one class NakamaGRPC used within the Default client. @mthakuri  how did you generate this one

**Comment by mthakuri** [comment] 2020-07-21 09:35
@sthaiya It's already there in the source build directory at https://github.com/heroiclabs/nakama-java/tree/master/build/generated/source/proto/main/grpc/com/heroiclabs/nakama/api. If you want to generate it by yourself then you can use the file at [https://github.com/heroiclabs/nakama/tree/master/apigrpc](url). The latest file generated some extra classes and function that caused me to ask the above question related to server support. I believe, the one inside the build directory was genereated with some previous version of server's .proto file. I then tried to use the recomplied jar in my project but came across ClassNotFound error in some cases. I still need to look further into these issues. I'll update if I'm able to solve it.

**Comment by mthakuri** [comment] 2020-07-26 15:35
@mofirouz Do I need to have the Nakama server running locally for test cases to pass?

**Comment by lugehorsam** [comment] 2020-08-05 16:20
@mthakuri @sthaiya fixed by #35 which packages all the relevant proto files inside the repo.

**Closed by lugehorsam** 2020-08-05 16:20 UTC
